# SPDX-FileCopyrightText: Copyright (c) 2026 Orange
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = ["*"]
SPDX-FileCopyrightText = "Copyright (c) Orange"
SPDX-License-Identifier = "MPL-2.0"
