# SPDX-FileCopyrightText: Copyright (c) 2025 Orange
# SPDX-License-Identifier: Mozilla Public License 2.0
#
# This software is distributed under the MPL-2.0 license.
# the text of which is available at https://www.mozilla.org/en-US/MPL/2.0/
# or see the "LICENSE" file for more details.

# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  PROJECT_NAME: cloudavenue

# * Import
includes: 
  go: ".taskfiles/golang.yml"
  license: ".taskfiles/license.yml"
  pre-commit: ".taskfiles/pre-commit.yml"
  tf: ".taskfiles/terraform.yml"
  yaml: ".taskfiles/yaml.yml"

# * Tasks
tasks:
  install:
    desc: Install required tools
    cmds:
      - task: go:install
      - task: license:install
      - task: pre-commit:install
      - task: tf:install

  init:
    desc: Initialize the project
    cmds:
      - task: provider:init
      - task: go:init
      - task: license:init
      - task: pre-commit:init
      - task: tf:init

  lint:
    desc: Run linters
    cmds:
      - task: license:lint
      - task: go:lint
      - task: go:actions:deps
      - task: go:actions:generate
      - task: tf:lint:tf:fmt-specific-dir
        vars:
          DIRECTORY: "examples"

  generate:
    desc: Generate code and docs
    cmds:
      - task: go:run
      - task: tf:lint:tf:fmt-specific-dir
        vars:
          DIRECTORY: "examples"
      - task: license:run

  # * Specific terraform provider
  provider:init:
    desc: Initialize the provider
    silent: true
    preconditions:
      - sh: test -f .env || test -f '{{.HOME}}/.cloud_avenue.source'
        msg: "❌ No .env or {{.HOME}}/.cloud_avenue.source file found. Please create one with the required variables. See CONTRIBUTING.md for more details."
    cmds:
      - |
        envfile="{{.HOME}}/.cloud_avenue.source"
        if [ -f .env ]; then
          envfile=".env"
        fi

        listOfVars=(
          "CLOUDAVENUE_ORG"
          "CLOUDAVENUE_USERNAME"
          "CLOUDAVENUE_PASSWORD"
        )

        echo "🔧 Checking if required variables are present in $envfile"

        for var in "${listOfVars[@]}"; do
          grep -q "$var" $envfile || echo "❌ $var not found" && echo "✅ $var found"
        done

        echo -e "\n📝 List of parameters available:"
        echo -e "In () the value used in the task"
        echo -e "💥 Required"
        echo -e " ✨ TF_TEST_NAME:\t({{.TF_TEST_NAME}}) - Specify the test to run"
        echo -e "🙈 Optionnal"
        echo -e " ✨ TF_LOG:\t\t({{.TF_LOG | default ""}}) - (Allowed values: trace, debug, info, warn, error) - Set the log level for terraform"
        echo -e " ✨ TF_ACC_RUN_TEST:\t({{.TF_ACC_RUN_TEST}}) - Specify the sub test to run"
        echo -e " ✨ TF_ACC_ONLY_PRINT:\t({{.TF_ACC_ONLY_PRINT | default false}}) - Only print the terraform configuration"
        echo -e " ✨ CLOUDAVENUE_DEBUG:\t({{.CLOUDAVENUE_DEBUG | default false}}) - Enable debug for cloudavenue"
        echo -e " ✨ NETBACKUP_DEBUG:\t({{.NETBACKUP_DEBUG | default false}}) - Enable debug for netbackup"
        echo -e " ✨ S3_DEBUG:\t\t({{.S3_DEBUG | default false}}) - Enable debug for s3"

        if [ "{{.CLOUDAVENUE_DEBUG }}" = "true" ] || [ "{{.NETBACKUP_DEBUG}}" = "true" ] || [ "{{.S3_DEBUG}}" = "true" ]; then
          if [ "{{.TF_LOG}}" = "" ]; then
            echo -e "\n🚨 DEBUG mode detected set TF_LOG variable to display the debug mode"
          fi
        fi 


  provider:test:
    desc: Run tests for the provider
    silent: true
    dotenv: ['.env', '{{.HOME}}/.cloud_avenue.source']
    deps:
      - task: provider:init
        silent: true
    requires:
      vars:
        - TF_TEST_NAME
    vars:
      TIMEOUT: "30m"
      TF_LOG: '{{.TF_LOG | default ""}}'
      TF_ACC_RUN_TEST: '{{.TF_ACC_RUN_TEST | default ""}}'
      TF_ACC_ONLY_PRINT: '{{.TF_ACC_ONLY_PRINT | default false}}'
      CLOUDAVENUE_DEBUG: '{{.CLOUDAVENUE_DEBUG | default false}}'
      NETBACKUP_DEBUG: '{{.NETBACKUP_DEBUG | default false}}'
      S3_DEBUG: '{{.S3_DEBUG | default false}}'
    env:
      TF_ACC: 1
    cmds:
      - echo -e "\n🔧 Running tests for {{.TF_TEST_NAME}}"
      - go test -v ./internal/testsacc/ -count=1 -timeout {{.TIMEOUT}} -run {{.TF_TEST_NAME}}

  provider:install:
    desc: Install provider locally
    silent: false
    cmds:
      - go install .
