name: generate

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths:
      - 'templates/**'
      - 'examples/**'  
      - 'internal/tests/**'
      - '**.go'
  
jobs:
  generate:
    name: Generate
    runs-on: arc-runners
    steps:
      - uses: actions/checkout@v4 # v3.5.0
      - uses: actions/setup-go@v5 # v4.0.0
        with:
          go-version-file: 'go.mod'
      - uses: nightstory/setup-task@v1
        with:
          enable-cache: true
          version: latest
      - run: task generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'task generate' command and commit."; exit 1)